### ISSUE TITLE
Installing OOMMFPy

### ISSUE THREAD

**Issue by Ponsudana** [davidcortesortuno/oommfpy#1]
Hi,
How can I install this pack using conda?

Thanks,

**Comment by Ponsudana** [comment]
I have just downloaded the zip file with source code and installed the library using pip. OOMMFPy works in my Jupyter notebook. 

Thanks,

**Comment by davidcortesortuno** [comment]
Ah ok, yes, I haven't made a PyPi package yet, but you can use `pip` and install the package from the main directory `pip install .`
Notice there are more features in the development branch (use `git checkout develop` in the package directory if you want to try it out), which I'm going to try to release soon

**Comment by Ponsudana** [comment]
@davidcortesortuno Yes, sure. Thank you.
