### ISSUE TITLE
compute_sk_number 

### ISSUE THREAD

**Issue by longlong-zhang** [davidcortesortuno/oommfpy#4]
Hello professor,
   There is a problem when i try to cakculate the skyrmion number.It seems that i have not properly import that function.
   I have read the docmention over times,but i did not found the instruction to import this module.
   Also, I have attached the error message in this submit.
   Hoping for you suggesstions.
![微信截图_20200504115023](https://user-images.githubusercontent.com/50805242/80935050-78bb3b00-8dfd-11ea-9297-7c813cfcd2c6.png)

**Comment by davidcortesortuno** [comment]
Hi, if you look at the first part of the `basics` notebook, https://github.com/davidcortesortuno/oommfpy/blob/master/doc/ipynb/basics.ipynb , you will notice that you have to initialise the class with your data file, and then use `.compute_sk_number` on the class object, e.g. `data.compute_sk_number(plane='xy', index=0)`

**Comment by longlong-zhang** [comment]
Got it!
Just as you mentioned, there is actually a example at the ```basics``` notebook.
Thanks very much for you prompt help!
